### ISSUE TITLE
Implement TRAPI 1.3 updates for workflow runner

### ISSUE THREAD

**Issue by capasfield** [ranking-agent/aragorn#108]
Ticket created based on discussion in Aragorn 8/5 team meeting ([agenda](https://docs.google.com/document/d/1x_ukP9eyy8ahb6ZlZAg78bdf6H2XxkcfGKR_r3WRcuM/edit?pli=1#))

**Comment by cbizon** [comment]
This would be better on the workflow runner repository.   But it has now been completed.
