### ISSUE TITLE
500 in /score

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/aragorn#11]
This query gives 37 results in strider, but returns no results from aragorn
```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "id": "UniProtKB:P52788",
                    "category": "biolink:Gene"
                },
                "n1": {
                    "category": "biolink:ChemicalSubstance"
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1"
                }
            }
        }
    }
}
```

**Comment by cbizon** [comment]
It looks like things are working down until the ranker. The attached file is the output from omnicorp overlay and in a quick scan, it looks fine. But when it gets sent to aragorn-ranker, we get back an empty message.


[breaksrank.json.txt](https://github.com/ranking-agent/aragorn/files/6416992/breaksrank.json.txt)

**Comment by cbizon** [comment]
Oops, it looks like that also gets through weighting ok, and it's scoring that causes the problem.

**Comment by cbizon** [comment]
[weighted_ansswer.json.txt](https://github.com/ranking-agent/aragorn/files/6417064/weighted_ansswer.json.txt)

Causes a 500 in /score

**Comment by PhillipsOwen** [comment]
updated code to insure that the kirchhoff() method gets node pairs, score is forced to 0 if it doesnt.
