### ISSUE TITLE
Monitor Prod?

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/aragorn#125]
Do we want some method for summarizing the prod logs?

Maybe a daily digest?  Could be as simple as something like:
PK, number of results_returned, time elapsed.

I don't know if there's something that the UI team is already doing along this vein, or how we can programmatically access the logs.

**Comment by jdr0887** [comment]
We can add a SocketAppender to the applications log configuration and pointed it at a centralized RENCI logging server.

**Comment by cbizon** [comment]
This is now handled by the SRI query logger
