### ISSUE TITLE
Creative mode queries for specific MONDOs do not return results.

### ISSUE THREAD

**Issue by DnlRKorn** [ranking-agent/aragorn#160]
This was observed when querying https://aragorn.renci.org/aragorn/docs

Creative mode query was launched for MONDO:0000440 multiple times. No results were returned from the ARA.

(I have a more through list of MONDO identifiers, but it's unclear if these queries spontaneously fail for these other values or simply did not return in this instance, but I specifically ran MONDO:0000440 a few times and each time could not get a response)

**Comment by cbizon** [comment]
It's possible that there just isn't an  answer.   Do you have access to the logs?  I'm assuming that strider is not returning results, and I guess the question would be whether that's legitimate or not...

**Comment by DnlRKorn** [comment]
I realized it was very likely an issue on my end with my nginx config rejecting payloads that were too large. If I find more errors I'll reopen.
