### ISSUE TITLE
Aragorn calling COHD with duplicate queries

### ISSUE THREAD

**Issue by CaseyTa** [ranking-agent/aragorn#17]
I was testing the following query through ARS, and noticed Aragorn is calling COHD four times, two of which are duplicate queries. Two of the queries are inverses of each other (the subject and object nodes are swapped in the edge). COHD returns essentially the same results either way, but it seems reasonable for an ARA to do this. But the second two queries are exact duplicates of the first two. This issue is potentially related to https://github.com/ranking-agent/aragorn/issues/10. 

The duplication of queries also occurred on the larger 3-hop query graph for December Demo's Workflow B, with Aragorn sending COHD 4 queries total (2 duplicates) for the single edge relevant to COHD (same as the query below)

I double checked our registration in SmartAPI, and I don't think COHD is double registered or anything, but please let me know if it might be something on our end that's causing this. 

This is not a high priority issue for us. 

```
{
  "message": {
    "query_graph": {
      "nodes": {
        "n1": {
          "categories": [
            "biolink:DiseaseOrPhenotypicFeature"
          ],
          "name": "Disease Or Phenotypic Feature"
        },
        "n0": {
          "ids": [
            "SNOMEDCT:197358007"
          ],
          "categories": [
            "biolink:DiseaseOrPhenotypicFeature"
          ],
          "name": "drug-induced liver injury"
        }
      },
      "edges": {
        "e0": {
          "subject": "n0",
          "object": "n1",
          "predicates": [
            "biolink:correlated_with"
          ]
        }
      }
    }
  },
  "logs": [],
  "status": null
}
```

**Comment by PhillipsOwen** [comment]
ARAGORN calls the strider service to parse through all the KPs. by chance have you tried that query against strider?

https://strider.renci.org/1.1/docs
if this is a strider

**Comment by cbizon** [comment]
I don't think there's a need to try that at the moment.   Strider is definitely overcalling things.  The exact duplicate is a little surprising, but we should have a new version deployed next week that dramatically removes the number of calls and will hopefully solve this problem.   Once that's deployed, we can retest.

**Comment by maximusunc** [comment]
Sending this query directly to Strider today (12/10/21), it is only sending one query to COHD.

**Comment by CaseyTa** [comment]
Thanks @maximusunc for following up on this.
