### ISSUE TITLE
Support fill operation

### ISSUE THREAD

**Issue by karafecho** [ranking-agent/aragorn#216]
This issue is related to development of the TCDC CQS Path A query (https://github.com/NCATSTranslator/Clinical-Data-Committee-Tracking-Voting/blob/main/GetCreative()_DrugDiscoveryRepurposing_RarePulmonaryDisease/Path_A/Path_A_no_overlay_chem_-reg_gene.json). Specifically, ARAX is the only ARA that supports the workflow `fill` operation. Path A requires two distinct `fill` operations. ARAX should be able to handle these requests but fails to do so due to TRAPI validation issues (see https://github.com/RTXteam/RTX/issues/2106). The reliance on a single ARA for this operation and other operations (e.g., `exclude`) has introduced a dependency that would be helpful to remove. Thus, the TCDC is requesting that ARAGORN implements a `fill` operation.

**Comment by maximusunc** [comment]
The TCDC is no longer trying to use the `fill` operation, so I'm going to close this.
