### ISSUE TITLE
has-part "electron"

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/aragorn#222]
https://ui.transltr.io/main/results?l=Diabetes%20Mellitus&i=MONDO:0005015&t=0&q=f2175bb7-43aa-4ed0-9c8f-574cbca1856e

Returns a bunch of subpaths like:

![image](https://github.com/ranking-agent/aragorn/assets/10744350/74555e2d-4fa2-4196-9efd-a727dee52eb6)

But electrons has an information content of 16 or so:

https://nodenormalization-sri.renci.org/1.4/get_normalized_nodes?curie=MESH%3AD004583&conflate=true&drug_chemical_conflate=false&description=false

So this should be filtered out.

**Comment by cbizon** [comment]
@maximusunc is this because the IC filtering didn't make it up to prod?  Or some other reason?

**Comment by maximusunc** [comment]
The IC filtering has been in prod for a while. But I looked into this this morning and found another major bug where we're actually filtering out the pinned node in this query. I'm working on a fix.

**Comment by cbizon** [comment]
Yeah, I suspect that's https://github.com/ranking-agent/aragorn/issues/223 ?   It might also be related to the issue that Abrar has been working on with subclasses?

**Comment by maximusunc** [comment]
Yes, I think they might all be somewhat related, at least by the filter function.
