### ISSUE TITLE
Hydron treats anything

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/aragorn#226]
For HIV associated nephropathy (treats) we are returning hydron which is no good.  I'm not 100% sure that hydron should be on an every-block list, but it should be on a predicate specific blocklist perhaps.  Or maybe we add it to an everything blocklist just for ARAGORN?

https://github.com/NCATSTranslator/Feedback/issues/618

**Comment by cbizon** [comment]
Another related issue is here: https://github.com/NCATSTranslator/Feedback/issues/701

In this case, the symptom is a bit different, but the basic idea is that hydron is appearing in the middle of a path and it's leading to a bunch of similar and bad results.

It's possible that https://github.com/ranking-agent/aragorn/issues/225 will take care of this as well?  Let's reevaluate once @uhbrar pushes the fix.

**Comment by cbizon** [comment]
Just tested on CI, hydron is no long returned as a treatment for HIV associated nephropathy.

**Comment by maximusunc** [comment]
Can this be closed?

**Comment by cbizon** [comment]
I think yes.  I'm slightly concerned that there are some timeout issues masking these kinds of results.  But I'll close for now.
