### ISSUE TITLE
Natalizumab for MS

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/aragorn#239]
There is a Test for Natalizumab treating MS.  We fail the test, and I confirm that in CI we are not returning Natalizumab as a result (id: UNII:3JB47N2Q2P). 

However, when I hit strider.ci with the lookup version of (treats, MS), I do get Natalizumab back (it should at least be coming from robokop).

So where is it going?   It's possible that when that cached result ran we didn't get it for some transient reason.  Or perhaps we did and it got downranked into the bottom 500, but that seems bad...

**Comment by uhbrar** [comment]
I just ran the MS test on CI and dev, and I see Natalizumab as a top result (within the top 10 results with a score of .99997) on both. Maybe this was a case of it being missed by the cache?

**Comment by cbizon** [comment]
Thanks - did you extend the timeouts at all? Maybe when things ran, there were KPs that weren't quite ready yet...

**Comment by uhbrar** [comment]
No, I only ran it with bypassing the cache, but didn't extend the timeout at all. Seems like a service may have been down when it ran the first time?
