### ISSUE TITLE
TRAPI Timeline: ARAs complete v1.2 implementations and register in SmartAPI

### ISSUE THREAD

**Issue by mmersmann** [ranking-agent/aragorn#24]
**Due Date:** September 1
**Note:** Implement 1.2 with asynch.
[TRAPI 1.1 to 1.2 Change Log](https://github.com/NCATSTranslator/ReasonerAPI/pull/277/files).
[ReasonerAPI Reference Ticket](https://github.com/NCATSTranslator/ReasonerAPI/issues/272)

**Comment by mmersmann** [comment]
Per Chris in Translator: RENCI Integration meeting: This is complete for external purposes. Internal work remaining.

**Comment by richakanwar13** [comment]
As per meeting on 9/17, this can be closed.
