### ISSUE TITLE
merged edge provenance

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/aragorn#252]
See https://github.com/NCATSTranslator/Feedback/issues/811

I think that what is possibly happening is that when we merge edges via the normal Translator rules, we are not correctly keeping all of the upstream aggregators correctly.    When ARAGORN does this merging, it's via reasoner-pydantic.  So I suspect an issue there, though have not confirmed.

**Comment by uhbrar** [comment]
Yeah, I think this is a reasoner-pydantic bug. I think when we do edge merging, we get all of the individual sources, but we aren't properly merging a single resource retrieving an edge from multiple sources. I'll get started on fixing that.

**Comment by colleenXu** [comment]
Perhaps related to these as well?
https://github.com/NCATSTranslator/Feedback/issues/814#issuecomment-2216896382
https://github.com/NCATSTranslator/Feedback/issues/815#issuecomment-2216905247
