### ISSUE TITLE
Aragorn providing edge_attribute_source without infores id information

### ISSUE THREAD

**Issue by vgardner-renci** [ranking-agent/aragorn#39]
See the most recent version of the workflow progress tracker / edge attribute source sheet.

https://docs.google.com/spreadsheets/d/1O1cMmYGxoIqP6xbzj6FG5owiKQVg57wx2O_XIA_hN_A/edit#gid=642301883

Rows at the top indicate in which workflows aragorn is returning edge attribute sources without infores id information.

**Comment by cbizon** [comment]
This needs to be reviewd.
