### ISSUE TITLE
Dev tools stand up, register in smartapi with “x-maturity: development”

### ISSUE THREAD

**Issue by richakanwar13** [ranking-agent/aragorn#74]
Due by Nov 8.

**Comment by richakanwar13** [comment]
Completed for node norm.

**Comment by PhillipsOwen** [comment]
although i have created a development deployment, at this time the current container image for strider does not support x-maturity, x-location and infores.

**Comment by richakanwar13** [comment]
Issues with Node norm. Phil working to resolve.

**Comment by PhillipsOwen** [comment]
strider image is now ready for dev deployment.

**Comment by PhillipsOwen** [comment]
all dev services noted above are running. some need more testing to insure that associated databases are running and connected.

**Comment by richakanwar13** [comment]
Websites are up, some more testing to be done.

**Comment by richakanwar13** [comment]
Complete as per meeting on 11/24.

**Comment by richakanwar13** [comment]
Re-opened based on the ARAGORN 12/3 meeting.

**Comment by YaphetKG** [comment]
Aragorn-dev is registered at smart api (http://smart-api.info/registry?q=d418acd9c9120ab89c4debfc8af3ad21) 
Aragorn-Prod's : http://smart-api.info/registry?q=86c92eba3d7b85720db2501fa32d6cdd

**Comment by richakanwar13** [comment]
Complete as of 12/8.
