### ISSUE TITLE
Current tools all add “x-maturity: production” and “infores” to all existing SmartAPI registrations

### ISSUE THREAD

**Issue by richakanwar13** [ranking-agent/aragorn#75]
- [x] Aragorn
- [x] Strider
- [x] Answer Coalescer
- [x] Ranker
- [x] Node Norm
- [x] Biolink lookup
- [x] Name resolution
- [x] KP Registry
- [x] Automat
- [x] Plater

**Comment by richakanwar13** [comment]
At this time the container image does not support x-maturity, x-location and infores.

**Comment by richakanwar13** [comment]
Phil trying to deploy Strider.

**Comment by PhillipsOwen** [comment]
Strider deploy corrected.

**Comment by PhillipsOwen** [comment]
there is a pending aragorn PR, so i am un-checking aragorn for now.

**Comment by PhillipsOwen** [comment]
aragorn PR has been implemented.

all products can now be considered frozen.

**Comment by richakanwar13** [comment]
One additional change for aragorn required.

**Comment by richakanwar13** [comment]
Complete as per meeting on 11/24.
