### ISSUE TITLE
Chunk RMQ

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/aragorn#81]
Within aragorn we use rabbit mq to communicate between worker threads.  That's done by pushing a strider response through the mq.   

But, there is a max size for rabbit mq messages.  So we need some chunking on the messages, which is probably going to complicate things....

But without it, we will always fail on strider results greater than X.

**Comment by kennethmorton** [comment]
It might be worth considering this partial serialization as capabilities of the reasoner-pydantic objects or Aragorn specific subclasses thereof.

**Comment by PhillipsOwen** [comment]
I am implementing a solution that would be to stream the strider response into a file and the file path be placed in the queue.

when the queue entry is handled it pulls the response from the file and moves on.

**Comment by cbizon** [comment]
Is this completed/deployed?
