### ISSUE TITLE
Local ARAGORN

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/aragorn#88]
ARAGORN receives TRAPI queries, which may contain workflows.   If a TRAPI query does not contain a workflow, a default workflow is run.

One of the possible workflow elements is "lookup" which consults data sources to provide all possible answers to the question.  In current ARAGORN, lookup is implemented by making an asynchronous TRAPI call to strider, which implements a federated lookup to all translator KPs.

We want to make a Local ARAGORN.   This would be another instance of the container, with a different configuration (Helm chart?)
When a lookup operation happens, then Local ARAGORN will not call strider, but will instead consult a single automat endpoint (either robokop or covidkop probably).   It's not quite as simple as replacing the strider URL with the automat URL because automat can only be consulted synchronously.

Additionally, there will soon be another operation (infer or creative lookup) which will have different implementations in the two ARAGORNs: Federated ARAGORN will use mined rules to query strider, while Local ARAGORN will simply consult a database of pre-calculated results.

**Comment by Hoid** [comment]
I think it'd be good to call this either _Internal_ or _Centralized_ ARAGORN instead of Local, because Local implies that it's on your local development machine. Internal implies that it's not dependent on an external source of truth/database, but if that's not true I think Centralized makes the most sense because it distinguishes it well from the Federated version.

**Comment by cbizon** [comment]
I think Centralized is good.  Consolidated maybe?

**Comment by cbizon** [comment]
https://docs.google.com/presentation/d/1sPaBtLW8Dj_fesng1pOkljRCaO_LKF7WvsZRKlodU5M/edit#slide=id.p

**Comment by cbizon** [comment]
* change value from strider_url to lookup_url (in values files; environment variables)
* Add a boolean value for lookup_synchronous in values, pass as environment variable
* 2 new instances, prod and dev, with lookup_url pointing to automat.renci.org/covidkop, synchronous=True
* Update "strider" function to "lookup" function, get lookup_url and synch from environment; pass to post

**Comment by cbizon** [comment]
This is complete, the local aragorn is called robokop b/c it makes use of the local robokop graph.
