### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/aragorn#9]
1. Rather than checking for 0-size responses from the component tools, we should check for status codes.
2. We should pass along errors and logs from the underlying elements, esp strider.
3. If a component fails, we should return whatever we got to up to that point, rather than returning nothing.  Everything after strider is a valid response, even if it does not have everything we want.

**Comment by cbizon** [comment]
Also, I think that if strider "returns nothing" we're printing an error message, returning an empty message, but returning a 200 status code.

If strider is returning an error code, then we should too.  If we return 200 we should return a trapi message with at least the query graph, plus empty knowledge_graph and results.

**Comment by PhillipsOwen** [comment]
corrected in the the PR #14 merge listed above.
