### ISSUE TITLE
Straighten out SMARTAPI registrations

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/aragorn#94]
https://aragorn.ci.transltr.io/1.2 is currently listed as 'x-maturity:development' but it should be 'x-maturity:staging'

https://aragorn.test.transltr.io/1.2 is listed ast 'x-maturity:test' but it should be 'x-maturity:testing'

**Comment by YaphetKG** [comment]
https://smart-api.info/ui/bfc3b5d9946777b3e9ffd0a7209b4d95 (aragorn ci registration) has been refreshed as `x-maturity: staging` .
test instance requires re-deployment.
