### ISSUE TITLE
Add Robokop ARA to the SmartAPI registry

### ISSUE THREAD

**Issue by capasfield** [ranking-agent/aragorn#97]
Discussed during the 7/22 Aragorn meeting ([agenda](https://docs.google.com/document/d/1x_ukP9eyy8ahb6ZlZAg78bdf6H2XxkcfGKR_r3WRcuM/edit?pli=1#) contains background info)

**Comment by YaphetKG** [comment]
Robokop ARA is registered in smart api
http://smart-api.info/registry?q=7913ecde63f1242dc8dbab2c952b6207 CI
http://smart-api.info/registry?q=1f8f40eb40d0843de572130ea3c2228a PROD
http://smart-api.info/registry?q=66a3e470c078ce3ca2de008c1f669e71 test
http://smart-api.info/registry?q=a488c0babcc47b196d119620bd2e5537 Dev
