### ISSUE TITLE
Make sure that the SRI services are also properly registered with SmartAPI

### ISSUE THREAD

**Issue by capasfield** [ranking-agent/aragorn#99]
Discussed during the 7/22 Aragorn team meeting

Check out the meeting notes for background info: https://docs.google.com/document/d/1x_ukP9eyy8ahb6ZlZAg78bdf6H2XxkcfGKR_r3WRcuM/edit?pli=1#

**Comment by YaphetKG** [comment]
All sri services have been registered, 
including aragorn robokop instances
